### ISSUE TITLE
[Enhancement]  Add option to confirm before overwriting file

### ISSUE THREAD

**Issue by benmoran56** [fingon/starless#2]
One enhancement idea would be to add the option to confirm before overwriting a file. 
For example, add an additional "preview" cli option that would instead print out the proposed changed lines. 

`starless --preview myfile.py`
`   -  from modulename import *`
`   + from modulename import thinga, thingb, thingc`

**Comment by fingon** [comment]
Typoed issue number. I guess I can take a look at this too, it should be fairly straightforward to do.

**Comment by benmoran56** [comment]
This isn't really a critical thing, so maybe a note in the README would be enough?
